/*
** EPITECH PROJECT, 2019
** Project Name
** File description:
** credit header
*/
#ifndef CREDIT_H_
#define CREDIT_H_

const char *credit =
"GAME DESIGN\n\nVICTOR HAMON\nMATTHIEU FUNARO\n\nGAME DEVELOPEMENT\n\nVICTOR \
HAMON\nMATTHIEU FUNARO\nYANN TSATSARIS\nANTHONY BOIZIER\n\nDRAWINGS\n\nTHOMAS \
HAMON\nVICTOR HAMON\n\nMUSIC\nJOE HISAISHI BUDOKAN\nTOBY FOX\n\n\n\n\n\nTHANKS"
;

#endif /* CREDIT_H_ */